name: Build Windows App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install flet

    - name: Build Windows app (no rich output)
      run: |
        cd src
        python -c "import subprocess; subprocess.run(['flet', 'build', 'windows'], env={**dict(os.environ), 'TERM': 'dumb'})"
      env:
        PYTHONIOENCODING: utf-8
        FORCE_COLOR: 0

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: NetDuty-Windows
        path: src/build/windows/**/*
