      - name: Build using Python script
        shell: cmd
        run: |
          cd src
          python -c "
import os
import sys
import subprocess

# Отключаем форматирование
os.environ['FORCE_COLOR'] = '0'
os.environ['TERM'] = 'dumb'
os.environ['PYTHONIOENCODING'] = 'utf-8'

# Запускаем сборку
try:
    result = subprocess.run(
        [sys.executable, '-m', 'flet', 'build', 'windows'],
        capture_output=True,
        text=True,
        encoding='utf-8',
        errors='ignore'
    )
    
    if result.stdout:
        print('STDOUT:', result.stdout)
    if result.stderr:
        print('STDERR:', result.stderr)
    
    sys.exit(result.returncode)
except Exception as e:
    print(f'Error: {e}')
    sys.exit(1)
"
