name: Build Linux App

on:
  push:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet pyinstaller
        
    - name: Build Linux App
      run: |
        pyinstaller --onefile --windowed --name "NetDuty" main.py
        
    - name: Upload Linux App
      uses: actions/upload-artifact@v4
      with:
        name: NetDuty-Linux
        path: dist/NetDuty
