name: Build NetDuty Clean

on:
  push:
    branches: [ main ]

jobs:
  build-clean:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install only flet
      run: |
        python -m pip install --upgrade pip
        pip install flet==0.10.0  # конкретная версия
        
    - name: Create flet.yaml
      run: |
        echo 'name: "NetDuty"
description: "NetDuty Application" 
publish: false' > flet.yaml
        
    - name: Build with Flet CLI
      run: |
        flet build linux --include-packages flet
        
    - name: Upload Result
      uses: actions/upload-artifact@v4
      with:
        name: NetDuty-Clean-Build
        path: build/linux
