name: Build with Nuitka

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install flet nuitka
        
    - name: Build with Nuitka
      run: |
        python -m nuitka --standalone --onefile main.py --output-filename=NetDuty
        
    - name: Upload App
      uses: actions/upload-artifact@v4
      with:
        name: NetDuty-Nuitka
        path: NetDuty
