name: Build Windows App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install flet

    - name: Build Windows app with Flet
      run: |
        cd src
        flet build windows
      
    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: NetDuty-Windows
        path: src/build/windows/**/*
