    - name: Build as folder
      run: |
        pyinstaller --windowed --name "NetDuty" main.py
        
    - name: Create portable ZIP
      run: |
        Compress-Archive -Path dist/NetDuty/* -DestinationPath NetDuty-Portable.zip
        
    - name: Upload portable app
      uses: actions/upload-artifact@v4
      with:
        name: NetDuty-Portable
        path: NetDuty-Portable.zip
