# .github/workflows/build-linux.yml
name: Build Linux Executable

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet pyinstaller
        
    - name: Build with PyInstaller
      run: |
        cd src
        pyinstaller --onefile \
          --windowed \
          --name NetDuty \
          --add-data ".::." \
          --hidden-import flet \
          --hidden-import flet.core \
          --hidden-import flet.utils \
          --exclude-module tkinter \
          --exclude-module matplotlib \
          --exclude-module pandas \
          main.py
        
    - name: Upload Linux Executable
      uses: actions/upload-artifact@v4
      with:
        name: NetDuty-Linux
        path: src/dist/NetDuty
