name: Build NetDuty
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install flet
      - run: flet build linux
      - uses: actions/upload-artifact@v4
        with:
          name: NetDuty-App
          path: build/linux
