name: Build Optimized Linux App

on:
  push:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet==0.24.1 pyinstaller
        
    - name: Build with optimizations
      run: |
        pyinstaller --clean --noconfirm \
          --name "NetDuty" \
          --onefile \
          --windowed \
          --add-data "Classes:Classes" \
          --exclude-module tkinter \
          --exclude-module matplotlib \
          --exclude-module pandas \
          main.py
        
    - name: Upload Linux App
      uses: actions/upload-artifact@v4
      with:
        name: NetDuty-Linux-Optimized
        path: dist/NetDuty
