name: Build Windows App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install flet

      - name: Build Windows app
        shell: pwsh
        run: |
          $env:FORCE_COLOR = "0"
          $env:TERM = "dumb"
          cd src
          python -c "import subprocess; import sys; result = subprocess.run(['flet', 'build', 'windows'], capture_output=True, text=True, encoding='utf-8', errors='ignore'); print('STDOUT:', result.stdout); print('STDERR:', result.stderr); sys.exit(result.returncode)"

      - name: Check build result
        shell: pwsh
        run: |
          if (Test-Path "src/build/windows") {
            Write-Host "✅ Build successful!"
            Get-ChildItem "src/build/windows" -Recurse
          } else {
            Write-Host "❌ Build failed - no output directory"
            exit 1
          }

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: NetDuty-Windows
          path: src/build/windows/**/*
