name: Build Windows App
on: [push, workflow_dispatch]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'
      - name: Install dependencies
        run: pip install flet
      - name: Build Windows App
        run: |
          cd src
          flet build windows
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: YourApp-Windows
          path: src/build/windows/**/*
