name: Build Windows Executable - Perfect

on:
  push:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet pyinstaller
        
    - name: Clean previous builds
      run: |
        cd src
        Remove-Item -Recurse -Force dist, build -ErrorAction SilentlyContinue
        Remove-Item -Force *.spec -ErrorAction SilentlyContinue
        
    - name: Build EXACTLY like Linux version
      run: |
        cd src
        pyinstaller --onefile --windowed --name NetDuty main.py
        
    - name: Upload Windows Executable
      uses: actions/upload-artifact@v4
      with:
        name: NetDuty-Windows-Perfect
        path: src/dist/NetDuty.exe
