name: Build NetDuty No Auto Install

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install flet pyinstaller
        
    - name: Build with hidden imports
      run: |
        pyinstaller --onefile \
        --name "NetDuty" \
        --hidden-import flet \
        --hidden-import flet.core \
        --hidden-import flet.utils \
        --add-data "$(python -c 'import flet; print(flet.__path__[0])'):flet" \
        main.py
        
    - name: Upload App
      uses: actions/upload-artifact@v4
      with:
        name: NetDuty-No-Auto-Install
        path: dist/NetDuty
