name: Build with cx_Freeze

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install cx_Freeze
      run: |
        pip install flet cx-freeze
        
    - name: Create setup.py
      run: |
        cat > setup.py << 'EOF'
        import sys
        from cx_Freeze import setup, Executable
        
        build_options = {
            "packages": ["flet"],
            "excludes": ["tkinter", "matplotlib", "pandas"],
            "include_files": []
        }
        
        base = None
        if sys.platform == "win32":
            base = "Win32GUI"
        
        setup(
            name="NetDuty",
            version="1.0",
            description="NetDuty App",
            options={"build_exe": build_options},
            executables=[Executable("main.py", base=base, target_name="NetDuty")]
        )
        EOF
    
    - name: Build with cx_Freeze
      run: |
        python setup.py build
        
    - name: Upload App
      uses: actions/upload-artifact@v4
      with:
        name: NetDuty-cxFreeze
        path: build/exe.linux-*
